# Generated by Django 3.1.4 on 2021-05-11 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210511_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watching_users',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
