# Generated by Django 3.1.4 on 2021-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210511_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
