# Generated by Django 3.1.4 on 2021-05-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210513_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
