# Generated by Django 3.1.4 on 2021-05-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210513_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-value']},
        ),
        migrations.RemoveField(
            model_name='bid',
            name='is_highest',
        ),
    ]
